[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/app/data"
name = "interviewer-roster-data"
